---
# 本项目所需的 Ansible Collections 依赖列表
# 安装方式: ansible-galaxy collection install -r collections/requirements.yml

collections:
  # 云平台支持
  - name: community.aws
    version: ">=6.0.0"
  - name: azure.azcollection
    version: ">=1.14.0"
  - name: google.cloud
    version: ">=1.12.0"
  - name: openstack.cloud
    version: ">=2.0.0"
  - name: alibaba.cloud
    version: ">=1.0.0"

  # 虚拟化支持
  - name: community.libvirt
    version: ">=1.3.0"
  - name: community.vmware
    version: ">=4.0.0"

  # 容器编排
  - name: community.kubernetes
    version: ">=2.0.0"
  - name: community.docker
    version: ">=3.0.0"

  # 消息队列
  - name: community.rabbitmq
    version: ">=1.3.0"

  # 数据库
  - name: community.mysql
    version: ">=3.0.0"
  - name: community.postgresql
    version: ">=2.4.0"
  - name: community.mongodb
    version: ">=1.6.0"

  # 监控系统
  - name: community.general
    version: ">=7.0.0"
  - name: community.datadog
    version: ">=1.0.0"
  - name: community.zabbix
    version: ">=2.0.0"
  - name: community.elastic
    version: ">=2.0.0"

  # 网络和防火墙
  - name: ansible.posix
    version: ">=1.5.0"

  # SSL 证书管理
  - name: community.crypto
    version: ">=2.14.0"

  # 系统管理
  - name: ansible.netcommon
    version: ">=5.0.0"
