advanced:
  title: 高级特性
  description: "涵盖 block/rescue、条件判断、循环、变量、handler 以及 include_tasks 的实战示例"
  topics:
    - id: block_rescue
      name: Block 与 Rescue
      doc: advanced/block_rescue/README.md
      example: advanced/block_rescue/playbook.yml
      summary: "使用 block/rescue/always 保障多步任务可回滚"
    - id: when_conditions
      name: When 条件
      doc: advanced/when_conditions/README.md
      example: advanced/when_conditions/playbook.yml
      summary: "通过 when 控制任务在不同系统上的执行"
    - id: loop_iteration
      name: Loop 循环
      doc: advanced/loop_iteration/README.md
      example: advanced/loop_iteration/playbook.yml
      summary: "解释 loop_control.loop_var 并遍历主机列表"
    - id: set_fact_vars
      name: set_fact 变量构建
      doc: advanced/set_fact_vars/README.md
      example: advanced/set_fact_vars/playbook.yml
      summary: "在运行时组合结构化变量并缓存"
    - id: handlers_notify
      name: Handler Notify 链路
      doc: advanced/handlers_notify/README.md
      example: advanced/handlers_notify/playbook.yml
      summary: "展示配置变更触发多级 handler 的流程"
    - id: include_tasks
      name: Include Tasks
      doc: advanced/include_tasks/README.md
      example: advanced/include_tasks/playbook.yml
      summary: "通过 include_tasks 拆分子任务并传递参数"

monitoring:
  title: 监控模块
  description: "主流监控系统的 Ansible 集成示例，包含 Nagios、Datadog、Zabbix 等监控平台的自动化配置"
  external_dependencies:
    - "community.general collection (Nagios)"
    - "community.datadog collection (Datadog)"
    - "community.zabbix collection (Zabbix)"
    - "Python libraries: python-nagios, datadog, zabbix-api, requests"
    - "监控服务器访问权限和 API 凭证"
  topics:
    - id: nagios_monitoring
      name: Nagios 监控集成
      doc: monitoring/nagios/README.md
      example: monitoring/nagios/playbook.yml
      summary: "传统开源监控系统的自动化配置，支持主机、服务、告警管理"
      external_deps:
        - "community.general collection"
        - "python-nagios library"
        - "Nagios 服务器 API 访问权限"
    - id: datadog_monitoring
      name: Datadog 云监控
      doc: monitoring/datadog/README.md
      example: monitoring/datadog/playbook.yml
      summary: "云原生监控和 APM 平台集成，支持基础设施、应用性能、日志聚合"
      external_deps:
        - "community.datadog collection"
        - "datadog Python library"
        - "Datadog API Key 和 App Key"
        - "Datadog Agent 安装权限"
    - id: zabbix_monitoring
      name: Zabbix 企业监控
      doc: monitoring/zabbix/README.md
      example: monitoring/zabbix/playbook.yml
      summary: "企业级开源监控解决方案，支持分布式监控和自动发现"
      external_deps:
        - "community.zabbix collection"
        - "zabbix-api Python library"
        - "Zabbix Server API 访问权限"
        - "Zabbix Agent 安装配置"

storage:
  title: 存储与文件系统
  description: "演示如何在 loopback 设备上练习 mount、lvol、filesystem 等存储模块，并提供安全演练指南"
  external_dependencies:
    - "ansible.posix collection (mount)"
    - "LVM2 与 ansible.builtin.lvol 模块运行所需的系统命令"
    - "losetup、dd、mkfs.xfs/mkfs.ext4 等磁盘模拟工具"
  topics:
    - id: storage_mount
      name: Loopback 挂载演练
      doc: storage/mount/README.md
      example: storage/mount/playbook.yml
      summary: "使用 ansible.posix.mount 管理临时 fstab 条目并验证挂载参数"
      external_deps:
        - "ansible.posix collection"
        - "dd/losetup 命令"
    - id: storage_lvol
      name: LVM 逻辑卷演练
      doc: storage/lvol/README.md
      example: storage/lvol/playbook.yml
      summary: "通过 ansible.builtin.lvol 在模拟 VG 中创建 LV，并结合 check 模式输出结果"
      external_deps:
        - "lvm2 套件"
        - "ansible.builtin.lvol 模块"
    - id: storage_filesystem
      name: 文件系统格式化演练
      doc: storage/filesystem/README.md
      example: storage/filesystem/playbook.yml
      summary: "借助 ansible.builtin.filesystem 在 loopback 设备上预览 mkfs 操作"
      external_deps:
        - "mkfs.xfs 或 mkfs.ext4 命令"
        - "ansible.builtin.filesystem 模块"

commands:
  title: 命令执行模块
  description: "演示 shell、command、raw、script 四个核心命令执行模块的使用差异、安全风险与最佳实践，包含中文文档和幂等性控制示例"
  topics:
    - id: shell
      name: Shell 模块
      doc: commands/shell/README.md
      example: commands/shell/playbook.yml
      summary: "通过系统 shell 执行命令，支持管道和重定向，包含安全说明和 set -e 错误处理"
      external_deps:
        - "目标主机 Python 环境"
        - "系统 shell（/bin/sh 或 /bin/bash）"
    - id: command
      name: Command 模块
      doc: commands/command/README.md
      example: commands/command/playbook.yml
      summary: "安全执行命令，不经过 shell 处理，避免 shell 注入风险，支持 creates/removes 幂等性控制"
      external_deps:
        - "目标主机 Python 环境"
    - id: raw
      name: Raw 模块
      doc: commands/raw/README.md
      example: commands/raw/playbook.yml
      summary: "直接 SSH 执行命令，适用于无 Python 环境，包含中文安全提醒和绕过机制说明"
      external_deps:
        - "SSH 连接"
        - "目标主机 shell 环境"
    - id: script
      name: Script 模块
      doc: commands/script/README.md
      example: commands/script/playbook.yml
      summary: "传输本地脚本到远程主机执行，支持复杂脚本逻辑和版本控制，包含示例脚本和中文注释"
      external_deps:
        - "目标主机 Python 环境"
        - "脚本执行权限"
      files:
        - "commands/script/files/example.sh"

web:
  title: Web 服务管理
  description: "提供 Nginx、Apache 以及通用 Web 配置的自动化示例，涵盖反向代理、静态站点发布、SSL 证书管理等常见场景"
  external_dependencies:
    - "community.general collection (ufw 模块)"
    - "nginx 或 apache2 软件包"
    - "SSL 证书（Let's Encrypt 或商业证书）"
  topics:
    - id: nginx
      name: Nginx Web 服务器
      doc: web/nginx/README.md
      example: web/nginx/playbook.yml
      summary: "高性能 HTTP 服务器和反向代理，支持负载均衡、静态内容服务、API 网关等场景"
      templates:
        - "web/nginx/templates/nginx.conf.j2"
        - "web/nginx/templates/vhost.conf.j2"
      external_deps:
        - "nginx 软件包"
        - "community.general collection"
    - id: apache2
      name: Apache2 Web 服务器
      doc: web/apache2/README.md
      example: web/apache2/playbook.yml
      summary: "久经考验的开源 Web 服务器，支持丰富的模块生态、虚拟主机和 PHP/Python 集成"
      templates:
        - "web/apache2/templates/apache.conf.j2"
        - "web/apache2/templates/security.conf.j2"
      external_deps:
        - "apache2 软件包"
        - "apache2 模块（rewrite、ssl、proxy 等）"
    - id: web_config
      name: 通用 Web 配置
      doc: web/web_config/README.md
      example: web/web_config/playbook.yml
      summary: "跨 Web 服务器的通用配置场景，包含反向代理、静态站点发布、SSL 证书管理和安全加固"
      templates:
        - "web/web_config/templates/proxy_nginx.conf.j2"
        - "web/web_config/templates/proxy_apache.conf.j2"
        - "web/web_config/templates/static_nginx.conf.j2"
        - "web/web_config/templates/static_apache.conf.j2"
      external_deps:
        - "nginx 或 apache2（根据配置选择）"
        - "SSL 证书文件"
